### PR TITLE
Feature/container strategy

### PR DESCRIPTION
**Pull request by simbuerg**

### CODE REVIEW

**Comment by simbuerg** [comment]
@Bazigeddon The failing tests look like something that is related to your SRC_FILE adjustements. Got an idea?

**Comment by simbuerg** [comment]
We need 'resumeable' strategies. Otherwise, it is absolutely annoying, if we fail a long running strategy half-way through (the polyjit strategy *cough*).
The clean sollution would be to generate an execution plan of all actions and persist the remaining ones on failure.
A quick fix could be: Just number them and specify a number to continue from. On failure we have to give the user the number of the last successful step.

**Comment by Bazigeddon** [comment]
There are two failing points at the moment. The one with the SRC_FILE, which I already fixed, and the unionfs testing suite, which tests nonsense in its current stage and could also be deleted since it already fulfilled its purpose.

**Comment by simbuerg** [comment]
TODO List:
1. Unbreak Travis: There are a few test-errors. Some are just output-changes, others look a bit 
    more involved.
2. 'container create' overwrites the configuration with invalid entries (valid for uchroot, but not 
    for the host).

**Comment by simbuerg** [comment]
The basedir is not correct when unionfs support is enabled.

```
CONFIGURE - Configure project source files
--- Chdir to /tmp/simbuerg/raw/gentoo-bzip2
--- Running ['/usr/bin/unionfs-fuse', '-o', 'allow_other,cow', '/tmp/simbuerg/raw/gentoo-bzip2/image=RW:/tmp/simbuerg/raw/gentoo-bzip2/base=RO', '/tmp/simbuerg/raw/gentoo-bzip2/union']
--- Chdir to /tmp/simbuerg/raw/gentoo-bzip2/union
--- Running ['/local/simbuerg/erlent/build/uchroot', '-E', '-A', '-C', '-w', '/', '-r', '/tmp/simbuerg/raw/gentoo-bzip2/union', '--', '/bin/touch', '/etc/portage/bashrc']
--- Chdir to /tmp/simbuerg/raw/gentoo-bzip2
--- Running ['/bin/fusermount', '-u', '/tmp/simbuerg/raw/gentoo-bzip2/union']
--- Chdir to /local/simbuerg/benchbuild
[Errno 2] No such file or directory: 'etc/portage/bashrc'
Execution of #4: '* gentoo-bzip2: Configure' failed.
```

**Comment by simbuerg** [comment]
And another error:

```
RUN - Execute the run action
/local/simbuerg/benchbuild/benchbuild/utils/actions.py:304: RuntimeWarning: Traceback (most recent call last):
  File "/local/simbuerg/benchbuild/benchbuild/utils/actions.py", line 297, in __call__
    result = a()
  File "/local/simbuerg/benchbuild/benchbuild/utils/actions.py", line 33, in wrapper
    res = f(*args, **kwargs)
  File "/local/simbuerg/benchbuild/benchbuild/utils/actions.py", line 331, in __call__
    result = action()
  File "/local/simbuerg/benchbuild/benchbuild/utils/actions.py", line 48, in wrapper
    res = f(*args, **kwargs)
  File "/local/simbuerg/benchbuild/benchbuild/utils/actions.py", line 33, in wrapper
    res = f(*args, **kwargs)
  File "/local/simbuerg/benchbuild/benchbuild/utils/actions.py", line 209, in __call__
    self._action_fn()
  File "/local/simbuerg/benchbuild/benchbuild/project.py", line 182, in run
    CFG["src_uri"] = self.src_uri
AttributeError: 'BZip2' object has no attribute 'src_uri'

  warnings.warn(formatted, category=RuntimeWarning)

Shutting down...
EXPERIMENT - OK

(bb-live) simbuerg@ligeti:/local/simbuerg/benchbuild% 

```

**Comment by Bazigeddon** [comment]
I unified the mount configs, but projects/gentoo/gentoo.py and utils/run.py are yet to be tested, since those are the only two files using the different mount configuration.

**Pull request merged**
