### PR TITLE
SLURM: support parallel execution of single versions

### PR DESCRIPTION
**Pull request by simbuerg**
This series of commits implements support for parallelization of (project, version)-tuples over multiple calls to srun for a SLURM cluster.

We implement this with 2 small extensions (one kinda ugly).

1. We accept version strings as part of a project name on the command line in the following format:
    `name/group@version`
    Example:
    `benchbuild run -E raw x264/benchbuild@3e5aed95cc`
    This is not intended as a general support for version specification on the CLI, because this will 
    overwrite the classmethod Project.verions() for the given project class and, therefore, not
    consider more than a single version for the same project.

2. We expand the available project versions during SLURM script generation. This will pull the sources 
    necessary for the listing of versions automatically on the host that generates the SLURM script.
    This expansion honors a custom sampling method and should just do what a user would expect.

### CODE REVIEW

**Comment by julianbreiteneicher** [comment]
Cool! Thanks for implementing this! :)

The creation of the slurm shell script works great. However, I'm having a few issues when running the script via slurm.

At first, I was getting errors like this:
```
COMPILE - Compile the project
$> Chdir to /scratch/breitenj/VaRA/benchbuild/results/GitBlameAnnotationReport-gravity-c_projects@8eb4b5cdd9_uuid_f7589c6f-fde6-4a64-a1eb-1e5c5ecdb4be
Hash file location: /scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD.hash
$> Running ['/bin/cp', '-ar', '--reflink=auto', '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD', '.']
ravity-c_projects@c53e92b8f0_uuid_0cec6ee3-b339-4525-8ec8-0f5914d0d7dd
$> Chdir to /scratch/breitenj/VaRA/benchbuild
Exception in step #0: * gravity: Compile
Traceback (most recent call last):
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/varats/utils/experiment_util.py", line 35, in __call__
    return self.__func(*args, **kwargs)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/benchbuild/utils/run.py", line 361, in wrap_in_builddir_func
    return func(self, *args, **kwargs)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/benchbuild/utils/run.py", line 376, in wrap_store_config
    return func(self, *args, **kwargs)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/varats/projects/c_projects/gravity.py", line 36, in compile
    self.download()
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/benchbuild/utils/download.py", line 305, in download_impl
    git("checkout", self.version)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/plumbum/commands/base.py", line 103, in __call__
    return self.run(args, **kwargs)[1]
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/plumbum/commands/base.py", line 240, in run
    return p.run()
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/plumbum/commands/base.py", line 201, in runner
    return run_proc(p, retcode, timeout)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/plumbum/commands/processes.py", line 232, in run_proc
    return _check_process(proc, retcode, timeout, stdout, stderr)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/plumbum/commands/processes.py", line 23, in _check_process
    proc.verify(retcode, timeout, stdout, stderr)
  File "/scratch/breitenj/VaRA/venv-vara/lib/python3.7/site-packages/plumbum/machines/base.py", line 26, in verify
    stderr)
plumbum.commands.processes.ProcessExecutionError: Command line: ['/usr/bin/git', 'checkout', 'c53e92b8f0']
Exit code: 1
Stderr:  | error: pathspec 'c53e92b8f0' did not match any file(s) known to git
```
Is this because BB does a shallow clone of the repository by default? The `Git` method in `utils/download.py` already has a `shallow_clone` parameter, but it's not exposed by the `with_git` decorator. After adding the parameter to the decorator and setting it to false in the project, this works now.

Now, I'm having a different issue. Now all runs fail with the following error:
```
fatal: destination path '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD' already exists and is not an empty directory.
```
I guess this is because all the parallel runs try to clone the repo simultaneously...

**Comment by simbuerg** [comment]
Great that it somehow works. I just tested up to the script generation :-).

You are correct, the shallow clone blocks us here. Strange that this works outside of SLURM, you should run into the same problems there. Easily fixable, by doing an unshallow on demand or by default. I can look into this.

The second part is stupid, because you already downloaded the source during script generation. As you store it on a shared NFS mount, you should not have to download it again. I think I have a better idea how to implement this and will look into it tonight using git workdirs.

**Comment by julianbreiteneicher** [comment]
> You are correct, the shallow clone blocks us here. Strange that this works outside of SLURM, you should run into the same problems there. Easily fixable, by doing an unshallow on demand or by default. I can look into this.

We did indeed have this issue previously outside of SLURM.
I made a workaround at the time, but then I forgot about it...

> The second part is stupid, because you already downloaded the source during script generation. As you store it on a shared NFS mount, you should not have to download it again. I think I have a better idea how to implement this and will look into it tonight using git worktree.

Yes, git worktree sounds like a good idea for this. Thanks for looking into it.

**Comment by simbuerg** [comment]
I _FINALLY_ understood what happened in your case, oh boy... :-)

1. benchbuild lists the versions vor your SLURM script: downloads the source
    (unshallowed, if not existing).
2. As you run the code on the cluster a single node will do a git checkout on the version you are running 
    (in the working copy, here is the bug).
3. Now another node comes along and checks, if it needs to download the sources.
    As it finds a git checkout, it will validate the content using the associated .hash file and find that the 
    hash does not match with the checkout content (because we did a git checkout after we downloaded 
    the source).
4. Now it will _wipe_ the filesystem content and the .hash file, not in one atomic operation ofc.

OUCH. I'm working on a fix, sorry for the inconvenience caused by this.

**Comment by simbuerg** [comment]
If you have time, you can give the latest revision a quick test on a small SLURM run. It should avoid the data races.

**Comment by julianbreiteneicher** [comment]
Unfortunately, there are still some issues with this.
I did another test and the first issue was the shallow clones again, so I set shallow_clone to false,
so that was easy to fix.

Now I  am getting different results for different revisions.
A few revisions fail with errors like
```
/bin/rm: cannot remove '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD/gravity.xcodeproj/project.pbxproj': No such file or directory
/bin/rm: cannot remove '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD/Makefile': No such file or directory
/bin/rm: cannot remove '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD/.git/worktrees/gravity-HEAD/logs': No such file or directory
/bin/rm: cannot remove '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD/.git/worktrees/gravity-HEAD1/ORIG_HEAD': No such file or directory
...
```

A few others fail with:
```
Checking out files:  49% (569/1144)   ^MChecking out files:  99% (1133/1144)   ^MChecking out files: 100% (1144/1144)   ^MChecking out files: 100% (1144/1144), done.
error: could not close '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD/.git/worktrees/gravity-HEAD2/index.lock'
fatal: Could not write new index file.
```

But most revisions fail with an error we've seen already:
```
fatal: destination path '/scratch/breitenj/VaRA/benchbuild/tmp/gravity-HEAD' already exists and is not an empty directory.
```

It seems like we still have some race conditions here.
Is it possible that for example the fact that the `Git()` method in `utils/download.py` is not synchronized is part of the problem?
In this method, the `source_required` method is called to determine if the repository is already cloned.
What if multiple slurm runs execute this method simultaniously in an unsynchronized way?

**Comment by julianbreiteneicher** [comment]
Btw, I've created PR PolyJIT/benchbuild#219 with a suggestion on how to allow a non-shallow git clone via the `with_git` decorator.

**Comment by simbuerg** [comment]
Synchronization would be great, but we are talking about synchronization accross python interpreters on different machines. So our only option would be flock'ing a file :-).
git worktree seems like a good idea in the first place (and I will keep it), but this modifies the index. I think it would be much simpler to change source_required to a beter non-hash based check.

When we are using git worktree, it should be enough to check, if the existing folder is a git repository with the correct remote. The rest is independent from the checkout.

**Comment by simbuerg** [comment]
Another try? We should converge at a good state now. Otherwise, I need to find some time to replicate it on SLURM myself..

**Comment by julianbreiteneicher** [comment]
I just tried it again and it seems to work really well now!! :)

**Comment by simbuerg** [comment]
I'm not sure how /scratch is configured. Maybe we run into consistency issues, so either we run fsync before unlocking, or we need to provide a way to download uncached.

I want to avoid uncached as much as possible because I don't think a repository like LLVM will find it funny, if we clone the repository for each revision we want xD

**Comment by julianbreiteneicher** [comment]
Yes, uncached is definately not a good idea.
I think the retry solution should be good enough for these cases...

**Comment by vulder** [comment]
I'm not 100% sure if this relates to your races but does it help to `lock` the worktree and only unlock afterwards?
`git worktree add --lock`
The docs mention that network storage can cause certain metadata files to be missing or out of sync.



```
--lock
Keep the working tree locked after creation. This is the equivalent of git worktree lock after git worktree add, but without race condition.
```
```
git worktree lock
If a working tree is on a portable device or network share which is not always mounted, lock it to prevent its administrative files from being pruned automatically. This also prevents it from being moved or deleted. Optionally, specify a reason for the lock with --reason.
```

**Comment by simbuerg** [comment]
That seems to be unrelated. The manpage states:

> If a working tree is on a portable device or network share which is not always mounted, lock it to prevent its administrative files from being pruned automatically. This also prevents it from being moved  or deleted. Optionally, specify a reason for the lock with --reason.

I believe (not sure) that @julianbreiteneicher problem is that some jobs want to add a worktree to the index "at the same time". I lock the region that adds/prunes the worktree index using python's interface to  fcntl, but sometimes that seems to fail. I'm not sure why. The manpage states that this locks accross NFS network shares as well.

Maybe the original source-clone got messed up during testing?

**Pull request merged**
