### PR TITLE
speed up slow build times for ./configure based projects

### PR DESCRIPTION
**Pull request by Kaufi-Jonas**
I have been investigating https://github.com/se-sic/VaRA/issues/1003. Concretely, I profiled the import time of the script `benchbuild/res/wrapping/run_compiler.py.inc`. I found that, at least for the VaRA-Tool-Suite, a substantial amount of time is being spent on importing plugins in the form of other projects and experiments which are not actually being used. So the main idea is to prevent that by overriding the benchbuild configuration through environment variables. Together with some other changes on VaRA's side, I managed to achieve about a 2x performance improvement in my tests.

The other thing that might give a speed improvement in the future is to use `importlib.metadata` to query the installed benchbuild version instead of `pkg_resources`. `pkg_resources` takes almost 100 ms on my machine to import, while  `importlib.metadata` is negligible. https://github.com/PolyJIT/benchbuild/commit/1ae6fdbbfd660fc4fd17765987aebf9da90dc834 won't do anything at the moment though because there are at least two third-party packages that also use  `pkg_resources` to set `__version__`.

In my opinion, the change to `benchbuild/res/wrapping/run_compiler.py.inc` should be completely transparent to the user and the necessary imports are still made when unpickling the project/compiler. @vulder @boehmseb @simbuerg  What do you think about this? Am I missing some detail where this might not work in certain cases?

### CODE REVIEW

**Comment by Kaufi-Jonas** [comment]
This is the import time profile after all optimizations. As you can see, most of the time on the benchbuild side is spent on importing packages related to the database. I am not too familiar with all the code but to me it seems that this can't really be reduced since the database is a core feature of benchbuild.

https://user-images.githubusercontent.com/14842772/227719369-8f306c02-52b0-493b-8887-913cfb9c08fb.png)

**Comment by simbuerg** [comment]
Thanks for working on this!

**Comment by simbuerg** [comment]
I never thought about it for long. But I think the sqlalchemy support can be removed "fairly" easily. The only real deep connection to the rest of benchbuild should be in ``benchbuild.utils.run.RunInfo`` and ``benchbuild.utils.actions``.
For a bit of perspective: ``sqlalchemy.migrate`` will go as soon as I finally get to unbreaking the github CI, because it blocks me from upgading to a newer sqlalchemy version.

The rest should work as you implemented it. Earlier versions of benchbuild relied on the standard pickle module. This relied on being able to have all necessary imports present in the unpickling python interpreter.

**Comment by Kaufi-Jonas** [comment]
Oh, I just saw https://github.com/PolyJIT/benchbuild/pull/549. I tested again with `sqlalchemy.migrate` removed. This yields another nice speed-up and also means that https://github.com/PolyJIT/benchbuild/commit/1ae6fdbbfd660fc4fd17765987aebf9da90dc834 actually has the intended effect. 

image

**Comment by Kaufi-Jonas** [comment]
> I never thought about it for long. But I think the sqlalchemy support can be removed "fairly" easily. The only real deep connection to the rest of benchbuild should be in `benchbuild.utils.run.RunInfo` and `benchbuild.utils.actions`. For a bit of perspective: `sqlalchemy.migrate` will go as soon as I finally get to unbreaking the github CI, because it blocks me from upgading to a newer sqlalchemy version.

I had a look again and it's definitely pretty easy to disable sqlalchemy support as well, thanks for your input. My idea is to add a switch for disabling the database in the benchbuild config. I am going to clean up my code so far and then push that into this PR as well.

**Comment by Kaufi-Jonas** [comment]
Force pushing really wasn't the call, anyway, now the damage is done.

Adding the configuration option and the respective if guards for db/transaction code was pretty straightforward. Below is also the import time profile after all these optimizations. For the VaRA-Tool-Suite, we are now at a ~4-5x faster invocation time for the wrapped compiler.

image

**Pull request merged**
