### PR TITLE
Use correct revision in 'with_git' decorator

### PR DESCRIPTION
**Pull request by julianbreiteneicher**

### CODE REVIEW

**Comment by vulder** [comment]
hmm, downloading should not be the problem the checkout needs to select the correct revision. In the local case this works and there we always download the current HEAD and switch to the needed revision in the results directory.

@simbuerg

**Comment by julianbreiteneicher** [comment]
@vulder The title of my PR is misleading. It's about the checkout, yes. Or more specifically about the git worktree that gets created in BB's results directory for each experiment run.
Currently, we don't specify the revision when we call the `Git` function, which means that BB
creates a git worktree with HEAD as selected revision for all experiment runs.
With this PR, we pass the correct revision to the `Git` function so that the worktree uses that instead of always HEAD.

**Comment by vulder** [comment]
ah, kk misread it. If it only applies to creating the worktree for the project and not the actuall download this should work.

**Comment by julianbreiteneicher** [comment]
I already applied that patch locally and tested it in my evaluation

**Comment by simbuerg** [comment]
LGTM. This slipped through during the shallow_clone merge. Git was too smart in the diff visualization ;-).

**Pull request merged**
